apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: main-i-02eed-2c27bc6
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-7097
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: main-i-02eed-2c27bc6
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.27"
  managementCluster:
    name: main-i-02eed-2c27bc6
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: main-i-02eed-2c27bc6
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: aws-eks-anywhere-test-docker-eab3708d-3dec-4b46-a6d9-20705ad62c1e-3
  clusterConfigPath: aws-eks-anywhere-test-docker-eab3708d-3dec-4b46-a6d9-20705ad62c1e-3
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-eks-anywhere-test-docker-eab3708d-3dec-4b46-a6d9-20705ad62c1e-3.git
  systemNamespace: default

---
